#!/bin/bash

# Auto-Build Environment Setup for AI Agent Development Learning Path
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo -e "${YELLOW}Starting Docusaurus development server...${NC}"
echo ""

# Start Docusaurus
npm run start &

# Wait for Docusaurus to be ready
wait_for_service 3000 "Docusaurus"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Docusaurus: http://localhost:3000"
echo ""
echo "Learning Path URL:"
echo "  http://localhost:3000/docs/ruta-aprendizaje-ia-agents/intro"
echo ""
echo "To stop services:"
echo "  Press Ctrl+C or run: pkill -f 'docusaurus start'"
echo ""
